# Changes here will be overwritten by Copier

_commit: 0.1.63
_src_path: git@bbpgitlab.epfl.ch:neuromath/python-template.git
author_email: ''
author_name: Blue Brain Project, EPFL
copyright_license: Apache License 2.0
copyright_year: '2023'
distribution_name: axon-synthesis
download_url: https://github.com/BlueBrain/AxonSynthesis
init_git: true
maintainer: Adrien Berchet (@adrien-berchet)
package_name: axon_synthesis
project_description: A package to synthesize artificial axons
project_name: Axon Synthesis
project_url: https://AxonSynthesis.readthedocs.io
repository_name: AxonSynthesis
repository_namespace: BlueBrain
repository_provider: github
setup_codeql: false
ssh_url: git@github.com:BlueBrain/AxonSynthesis.git
tracker_url: https://github.com/BlueBrain/AxonSynthesis/issues
use_pyproject_toml: true
version: 0.1.0.dev0

# End of Copier answers
